/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gimnasio_GUI;

/**
 *
 * @author Tacho
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Tclientes = new javax.swing.JButton();
        jButton_Tprofesores = new javax.swing.JButton();
        jButton_addCliente = new javax.swing.JButton();
        jButton_close = new javax.swing.JButton();
        jButton_addProfesore = new javax.swing.JButton();
        jButton_addProfesore1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Tclientes.setText("Clientes registrados");
        jButton_Tclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TclientesActionPerformed(evt);
            }
        });

        jButton_Tprofesores.setText("Profesores registrados");
        jButton_Tprofesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TprofesoresActionPerformed(evt);
            }
        });

        jButton_addCliente.setText("Agregar Cliente");
        jButton_addCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addClienteActionPerformed(evt);
            }
        });

        jButton_close.setText("cerrar sesión");
        jButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closeActionPerformed(evt);
            }
        });

        jButton_addProfesore.setText("Agregar Rutina");
        jButton_addProfesore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addProfesoreActionPerformed(evt);
            }
        });

        jButton_addProfesore1.setText("Agregar Profesor");
        jButton_addProfesore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addProfesore1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_close)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_addCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Tprofesores, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_addProfesore1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_addProfesore, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Tclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(165, 165, 165))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jButton_addProfesore)
                .addGap(18, 18, 18)
                .addComponent(jButton_addProfesore1)
                .addGap(18, 18, 18)
                .addComponent(jButton_addCliente)
                .addGap(18, 18, 18)
                .addComponent(jButton_Tprofesores)
                .addGap(18, 18, 18)
                .addComponent(jButton_Tclientes)
                .addGap(85, 85, 85)
                .addComponent(jButton_close)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TclientesActionPerformed

    private void jButton_TprofesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TprofesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TprofesoresActionPerformed

    private void jButton_addClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_addClienteActionPerformed

    private void jButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_closeActionPerformed

    private void jButton_addProfesoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addProfesoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_addProfesoreActionPerformed

    private void jButton_addProfesore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addProfesore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_addProfesore1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Tclientes;
    private javax.swing.JButton jButton_Tprofesores;
    private javax.swing.JButton jButton_addCliente;
    private javax.swing.JButton jButton_addProfesore;
    private javax.swing.JButton jButton_addProfesore1;
    private javax.swing.JButton jButton_close;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
